### ISSUE TITLE
Develop client login page

### ISSUE THREAD

**Issue by harsh-r-dave** [shivam1841/MyTracker#8]
Design login page, and implement back-end logic to allow client to login to the system

**Comment by hlac** [comment]
Is this a user story or task?


Regards,
Hao C. Lac, Ph.D. (Computational Science)

**Comment by harsh-r-dave** [comment]
Task as well as user story.

**Comment by hlac** [comment]
There is no such thing.


Regards,
Hao C. Lac, Ph.D. (Computational Science)

**Comment by shivam1841** [comment]
It is a user story

**Comment by shivam1841** [comment]
Its a task.. Only designing of the client login page...

**Comment by hlac** [comment]
What is the verdict?


Regards,
Hao C. Lac, Ph.D. (Computational Science)

**Comment by harsh-r-dave** [comment]
fixed
